[package]
name = "s3_downloader_lambda"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_runtime = "0.11"
aws-config = "1"
aws-sdk-s3 = "1"
aws_lambda_events = "0.13"
serde_json = "1"
tokio = { version = "1", features = ["full"] }
